
name: CI pipeline
on:
  push: ~
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        node_version:
          - 15.14.0
          - 16.13.0
          - 17.1.0

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node_version }}

    steps:
      - name: Code check-out
        uses: actions/checkout@v2

      - name: Node.js set-up
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Running tests with coverage
        run: npm run test:coverage

      - name: Test report (dorny)
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report (dorny)
          path: test-reports/junit.xml
          reporter: jest-junit

      - name: Test report (EnricoMi)
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-reports/junit.xml
          check_name: Test report (EnricoMi)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          env_vars: OS,NODE_VERSION
